project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "Echin, Xinya"
    right: "MUSA 550 Final"
  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: backpack
        href: https://musa-550-fall-2024.github.io/course/
        text: "Class Website"
      - icon: github
        text: "Our GitHub"
      - icon: mortarboard
        href: https://www.design.upenn.edu/
        text: "Stuart Weitzman School of Design"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: intro.qmd
        text: Introduction
      - section: 
        text: Analysis
        contents:
          - href: analysis.ipynb 
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    